- name: "Check for File Extension {{ extension }}"
  local_action: stat path={{ temp_search_file_name }}
  register: temp_search_file
  with_first_found:
    - files:
      - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/{{ common_hostname }}.{{ extension }}"
      - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/{{ inventory_hostname }}.{{ extension }}"
      - "{{ inventory_dir }}/host_vars/{{ common_hostname }}.{{ extension }}"
      - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}.{{ extension }}"
      - "{{ inventory_dir }}/host_vars/{{ extension }}"
      skip: true
  loop_control:
    loop_var: temp_search_file_name

- set_fact: {"{{ var_name }}": "{{ temp_search_file.results[0].stat.path }}"}
  when: (temp_search_file.results | length) == 1

- set_fact: {"{{ var_name }}": ""}
  when: (temp_search_file.results | length) == 0

