# Query if Var is merged already
- set_fact:
    temp_test_variable: "{{ vars[var_name + '_merged'] | default(false) }}"

# Merge
- set_fact:
    temp_merge_variable: "{{ vars[var_name + '_all'] | default([]) }} + {{ vars[var_name] | default([]) }}"
  when: not temp_test_variable

- set_fact:
    temp_merge_variable: "{{ temp_merge_variable }} + {{ vars[var_name + '_' + group_name] | default([]) }}"
  with_items: "{{ group_names }} "
  loop_control:
    loop_var: group_name
  when: not temp_test_variable

- set_fact: {"{{ var_name }}": "{{ temp_merge_variable }}"}
  when: not temp_test_variable
# Merge end

# Remember that this var is merged already so it does not get merged a 2nd time
- set_fact: {"{{ var_name }}_merged": true}
  when: not temp_test_variable

