#!/bin/bash
MY_COMMAND="ssh-client";
SCRIPT_SOURCE=$(readlink -f ${BASH_SOURCE});
if [[ "${1:-}" == "--quiet" ]];
then
    shift;
    . "${SCRIPT_SOURCE%/*/*}/_router.sh" --quiet --host-script "${BASH_SOURCE}" "${MY_COMMAND}" "$@";
elif [[ "${1:-}" == "--debug" ]];
then
    shift;
    . "${SCRIPT_SOURCE%/*/*}/_router.sh" --debug --host-script "${BASH_SOURCE}" "${MY_COMMAND}" "$@";
elif [[ "${1:-}" == "--verbose" ]];
then
    shift;
    . "${SCRIPT_SOURCE%/*/*}/_router.sh" --verbose --host-script "${BASH_SOURCE}" "${MY_COMMAND}" "$@";
else
    . "${SCRIPT_SOURCE%/*/*}/_router.sh" --host-script "${BASH_SOURCE}" "${MY_COMMAND}" "$@";
fi;
